using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ScannerDrivers.TWAIN.Contants.Enum
{
    /// <summary>
    /// Language Constants
    /// </summary>
    public enum Languages : short
    {
        USERLOCALE = -1,
        DAN = 0,
        DUT = 1,
        ENG = 2,
        FCF = 3,
        FIN = 4,
        FRN = 5,
        GER = 6,
        ICE = 7,
        ITN = 8,
        NOR = 9,
        POR = 10,
        SPA = 11,
        SWE = 12,
        USA = 13,
        AFRIKAANS = 14,
        ALBANIA = 15,
        ARABIC = 16,
        ARABIC_ALGERIA = 17,
        ARABIC_BAHRAIN = 18,
        ARABIC_EGYPT = 19,
        ARABIC_IRAQ = 20,
        ARABIC_JORDAN = 21,
        ARABIC_KUWAIT = 22,
        ARABIC_LEBANON = 23,
        ARABIC_LIBYA = 24,
        ARABIC_MOROCCO = 25,
        ARABIC_OMAN = 26,
        ARABIC_QATAR = 27,
        ARABIC_SAUDIARABIA = 28,
        ARABIC_SYRIA = 29,
        ARABIC_TUNISIA = 30,
        ARABIC_UAE = 31,
        ARABIC_YEMEN = 32,
        BASQUE = 33,
        BYELORUSSIAN = 34,
        BULGARIAN = 35,
        CATALAN = 36,
        CHINESE = 37,
        CHINESE_HONGKONG = 38,
        CHINESE_PRC = 39,
        CHINESE_SINGAPORE = 40,
        CHINESE_SIMPLIFIED = 41,
        CHINESE_TAIWAN = 42,
        CHINESE_TRADITIONAL = 43,
        CROATIA = 44,
        CZECH = 45,
        DANISH = DAN,
        DUTCH = DUT,
        DUTCH_BELGIAN = 46,
        ENGLISH = ENG,
        ENGLISH_AUSTRALIAN = 47,
        ENGLISH_CANADIAN = 48,
        ENGLISH_IRELAND = 49,
        ENGLISH_NEWZEALAND = 50,
        ENGLISH_SOUTHAFRICA = 51,
        ENGLISH_UK = 52,
        ENGLISH_USA = USA,
        ESTONIAN = 53,
        FAEROESE = 54,
        FARSI = 55,
        FINNISH = FIN,
        FRENCH = FRN,
        FRENCH_BELGIAN = 56,
        FRENCH_CANADIAN = FCF,
        FRENCH_LUXEMBOURG = 57,
        FRENCH_SWISS = 58,
        GERMAN = GER,
        GERMAN_AUSTRIAN = 59,
        GERMAN_LUXEMBOURG = 60,
        GERMAN_LIECHTENSTEIN = 61,
        GERMAN_SWISS = 62,
        GREEK = 63,
        HEBREW = 64,
        HUNGARIAN = 65,
        ICELANDIC = ICE,
        INDONESIAN = 66,
        ITALIAN = ITN,
        ITALIAN_SWISS = 67,
        JAPANESE = 68,
        KOREAN = 69,
        KOREAN_JOHAB = 70,
        LATVIAN = 71,
        LITHUANIAN = 72,
        NORWEGIAN = NOR,
        NORWEGIAN_BOKMAL = 73,
        NORWEGIAN_NYNORSK = 74,
        POLISH = 75,
        PORTUGUESE = POR,
        PORTUGUESE_BRAZIL = 76,
        ROMANIAN = 77,
        RUSSIAN = 78,
        SERBIAN_LATIN = 79,
        SLOVAK = 80,
        SLOVENIAN = 81,
        SPANISH = SPA,
        SPANISH_MEXICAN = 82,
        SPANISH_MODERN = 83,
        SWEDISH = SWE,
        THAI = 84,
        TURKISH = 85,
        UKRANIAN = 86,
        ASSAMESE = 87,
        BENGALI = 88,
        BIHARI = 89,
        BODO = 90,
        DOGRI = 91,
        GUJARATI = 92,
        HARYANVI = 93,
        HINDI = 94,
        KANNADA = 95,
        KASHMIRI = 96,
        MALAYALAM = 97,
        MARATHI = 98,
        MARWARI = 99,
        MEGHALAYAN = 100,
        MIZO = 101,
        NAGA = 102,
        ORISSI = 103,
        PUNJABI = 104,
        PUSHTU = 105,
        SERBIAN_CYRILLIC = 106,
        SIKKIMI = 107,
        SWEDISH_FINLAND = 108,
        TAMIL = 109,
        TELUGU = 110,
        TRIPURI = 111,
        URDU = 112,
        VIETNAMESE = 113
        //NOTE: when adding to this list, also update Language->Set()
    }

}
